### ISSUE TITLE
thank you, and report bugs of the demo.ipynb

### ISSUE THREAD

**Issue by tabeworks** [chenyuntc/simple-faster-rcnn-pytorch#2]
cell 1: "util" should be "utils"
cell 2: no folder named "assets" with demo.jpg inside
cell 3: "PermissionError: [Errno 13] Permission denied: '/home/username/.torch/models/vgg16-397923af.pth' "  (ubuntu 16.04)

**Comment by chenyuntc** [comment]
ACK ,  thanks!  I'll fix  tomorrow.

**Comment by chenyuntc** [comment]
Thanks for your report, It's bugs imported from [refactoring](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/commit/c5a2b289a4f000ba943e8473415fad095f7846ec)---the IDE can not refactor code in notebook. It's now fixed by  [this commit](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/commit/2a9496753b9b274b5fad2f5bb2eb03590cff6d4e), feel free to reopen it if you have any question.

P.S. cell3 error seems to be the problem of system privilege, but I still prevent it by avoid loading torchvision model.
